global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow-server:5000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
